Added WString support
S7NetPlus/s7netplus pull request #363
Opened 2021-01-24 11:57 UTC by MCPC10

Added support for WStrings.

2021-01-25 17:31 UTC, scamille approved these changes

2021-01-25 20:03 UTC, mycroes requested changes
Hi @MCPC10,

Thanks a lot for your changes. I only have some minor comments, if you can fix those I'll merge the PR.

Regards,
Michael

2021-01-25 20:18 UTC, MCPC10 commented on S7.Net/Types/S7String.cs
> +            if (reservedLength >= byte.MaxValue) throw new ArgumentException($"The maximum string length supported is {byte.MaxValue}.");
In the siemens doc they say that 254 is the maximum for a S7String (it's in german): https://support.industry.siemens.com/cs/mdm/109011420?c=63689840011&lc=de-DE

2021-01-25 20:25 UTC, MCPC10 commented on S7.Net/Types/S7WString.cs
> +            int size = ((bytes[0] << 8) & 0xFF) | (bytes[1] & 0xFF);
100% correct xD

2021-01-25 20:52 UTC, mycroes commented on S7.Net/Types/S7String.cs
> +            if (reservedLength >= byte.MaxValue) throw new ArgumentException($"The maximum string length supported is {byte.MaxValue}.");
Can you correct the size in the error message as well?

2021-01-25 20:53 UTC, mycroes commented
Please change the S7string max length error message, other changes are fine.

2021-01-26 16:50 UTC, MCPC10 commented
Isn't it better to use a constant instead of byte.MaxValue -1?

2021-01-26 16:50 UTC, MCPC10 commented on S7.Net/Types/S7String.cs
> +            if (reservedLength >= byte.MaxValue) throw new ArgumentException($"The maximum string length supported is {byte.MaxValue}.");
No problem but isn't it better to use a constant instead of byte.MaxValue -1?

2021-01-26 22:06 UTC, mycroes commented on S7.Net/Types/S7String.cs
> +            if (reservedLength >= byte.MaxValue) throw new ArgumentException($"The maximum string length supported is {byte.MaxValue}.");
Yes of course, but I would approve if you'd put in the value just as well! 😄

2021-01-27 16:57 UTC, MCPC10 commented on S7.Net/Types/S7String.cs
> +            if (reservedLength >= byte.MaxValue) throw new ArgumentException($"The maximum string length supported is {byte.MaxValue}.");
Another thing, isn't it better when we use ArgumentOutOfRangeException instead of ArgumentException? (just an idea xD)

2021-01-27 17:54 UTC, mycroes approved these changes

2021-01-27 17:55 UTC, merged

2021-01-27 17:56 UTC, mycroes commented
Thanks @MCPC10 for your contribution! Also thank you @scamille for the initial review!